apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: dvwa-ingress
  namespace: dvwa
spec:
  tls:
  - hosts:
    - dvwa.example.com
    secretName: default-server-secret-dvwa
  rules:
  - host: dvwa.example.com
    http:
      paths:
      - path: /
        backend:
          serviceName: dvwa
          servicePort: 80
