apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: hackazon-ingress
  namespace: hackazon
spec:
  tls:
  - hosts:
    - hackazon.example.com
    secretName: default-server-secret-hackazon
  rules:
  - host: hackazon.example.com
    http:
      paths:
      - path: /
        backend:
          serviceName: hackazon
          servicePort: 80
